version: '3.8'

services:
  client:
    build: ./client
    ports:
      - '3000:3000'
    depends_on:
      - server
    restart: always

  server:
    build: ./server
    ports:
      - '5000:5000'
    env_file:
      - ./server/.env
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    restart: always

  nginx:
    build: ./nginx
    ports:
      - '80:80'
    depends_on:
      - client
      - server
    restart: always

volumes:
  mongo-data:
